### ISSUE TITLE
Compatibility issue on Safari for POST method using URLSearchParams

### ISSUE THREAD

**Issue by jiangyue12392** [Reine0017/team-36-codeu#14]

**Comment by Reine0017** [comment]
which branch was it that had this issue?

**Comment by jiangyue12392** [comment]
> which branch was it that had this issue?

Actually, it is in the master branch now. You can check the feed.html page

**Comment by jiangyue12392** [comment]
Closed by #44 that refactors the code path and uses GET method for requests from `feed`.
