### ISSUE TITLE
Clicking 'x' to exit the 'Add review' popup reloads the page

### ISSUE THREAD

**Issue by potay** [Reine0017/team-36-codeu#35]
When a user clicks a marker, an 'Add review' popup appears. If the user does not want to add a review, the user clicks the 'x' button on the top right. This causes the whole page to load and the map has to be reloaded (which is currently slow).

It might make more sense for us to just hide the popup, instead of reloading the whole page.

**Comment by Reine0017** [comment]
fixed - changes pushed to ReineUI-maps branch
